# Generated by Django 2.1.2 on 2018-11-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
