# Generated by Django 2.1.2 on 2018-11-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20181128_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='tenant',
        ),
    ]
